### ISSUE TITLE
Blog post question

### ISSUE THREAD

**Issue by EvgenyKarkan** [yahoo/YMTreeMap#2]
Where can I find source code for this tutorial?
https://yahooeng.tumblr.com/post/141143817861/using-nsurlprotocol-for-testing

It seems mentioned github link is not valid anymore.

**Comment by adamkaplan** [comment]
Closing this because it isn't related to this project. I guess you're just looking for any place to ask a question of a Yahoo person?

I'm familiar with the author of that post, Roberto Osorio-Goenaga, but he hasn't worked here for a while. You can try to find him on Twitter/FB/LinkedIn and maybe he knows where the sample code is. (There's a chance it no longer exists).

**Comment by dbgrandi** [comment]
@diatrevolo, do you have that code still?

**Comment by EvgenyKarkan** [comment]
> I guess you're just looking for any place to ask a question of a Yahoo person?

Exactly, thanks.

**Comment by diatrevolo** [comment]
Hi, sorry just saw this. I do have the code, or rather the code exists, but it can't be posted without an ok from Yahoo!. It was released with Yahoo! copyright headers, and removed because of them. Unfortunately, it's out of my hands at this time. cc @EvgenyKarkan @dbgrandi @adamkaplan
