### ISSUE TITLE
Space between cells

### ISSUE THREAD

**Issue by MickaelCruzDB** [yahoo/YMTreeMap#7]
Hi! Thanks for your great job. How to increase the space between cells? 

Thanks!

**Comment by adamkaplan** [comment]
The actual rendering is not covered by this project because you may choose to use one of many possible application-specific methods such as: UICollectionView, OpenGL, Metal, CoreGraphics, UIViews, etc.

However an example is provided for the collection view method. What I did there was to inset the collection view cell content by 1 pixel, thereby creating 2 pixels space between each cell (1 pixel per cell). 
https://github.com/yahoo/YMTreeMap/blob/479b92db403fb7a3bee4d16bd855a2fba39ac165/Example/YMTreeMap/CollectionViewCell.swift#L51

If you wanted to provide much more space between cells, inset will not work well. In that case you should actually change the cell positions. The proper way to do this would be to apply a scaling formula that keeps the spacing (horizontal and vertical) in proportion.
